<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "homework1";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'Assassins Creed Valhalla', 'PS5', 'Aventura', '/resources/img/valhalla.png', 'Embark on a Viking adventure in England', 'yes', 4.99)",
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'Warframe', 'PC', 'Aventura', '/resources/img/warframe.png', 'Farm and lose your life', 'yes', 2.99)",
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'Vampire Survivors', 'PC', 'Esports', '/resources/img/VampireSurvivors.png', 'Experience the thrill of virtual football', 'yes', 5.99)",
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'The Legend of Zelda: Breath of the Wild', 'Nintendo', 'Aventura', '/resources/img/botw.jpg', 'Embark on an epic journey in Hyrule', 'yes', 6.99)",
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'Rocket League', 'PC', 'Esports', '/resources/img/rocket-league.jpg', 'Soccer meets vehicular mayhem', 'yes', 3.99)",
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'Minecraft', 'PC', 'RPG', '/resources/img/Minecraft.png', 'Enter the futuristic world of Night City', 'yes', 7.99)",
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'Among Us', 'PC', 'Puzzle', '/resources/img/among-us.jpg', 'Unmask the impostors in your crew', 'yes', 2.49)",
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'The Binding Of Isaac', 'Nintendo', 'Aventura', '/resources/img/isaac.jpg', 'Build, explore, and survive in blocky worlds', 'yes', 4.49)",
                "INSERT INTO " + schema + ".GAME (ID, NOM, CONSOLA, GENERE, IMAGEURL, DESCRIPCIO, DISPONIBILITAT, PREULLOGUERSETMANAL) VALUES (NEXT VALUE FOR GAME_GEN, 'Battlefield', 'Xbox', 'Accio', '/resources/img/battlefield.jpg', 'Battle royale action at its finest', 'yes', 6.49)",
                "INSERT INTO " + schema + ".CUSTOMER (ID, EMAIL, USUARI, NOM, COGNOM, CONTRASENYA) VALUES (NEXT VALUE FOR CUSTOMER_GEN, ',dfxkmdfm@gmail.com', 'ponderingorb', 'Maname', 'Jeff', 'contrasenya')",
                "INSERT INTO " + schema + ".CREDENTIALS (ID, USERNAME, PASSWORD) VALUES (NEXT VALUE FOR CREDENTIALS_GEN, 'sob', 'sob')"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
